AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service


Resources:
  DakobedTranscriptionsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
      BinaryMediaTypes:
        - application/audio

  DakobedModelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: model-layer.zip
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: python3.6

  TranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranscriptionFunction
      Runtime: python3.6
      Handler: handler.lambda_handler
      CodeUri: ./handlers/transcriptions/
      MemorySize: 512
      Timeout: 30
      Events:
        TranscriptionSQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:710339184759:DakobedTranscriptionQueue
            BatchSize: 10
            Enabled: true
      Policies:
        - SQSSendMessagePolicy:
            QueueName: DakobedTransformQueue
        - S3FullAccessPolicy:
            BucketName: dakobed-transcriptions
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedGuitarTranscriptions
      Layers:
        - arn:aws:lambda:us-west-2:347034527139:layer:tf_1_11_keras:1
        - !Ref DakobedModelLayer

  InitiateTransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InitiateTransformFunction
      Runtime: python3.6
      Handler: handler.handler
      CodeUri: ./handlers/initiateTransforms/
      Timeout: 30
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:710339184759:InitiateTransformsQueue
            BatchSize: 10
            Enabled: true
      Policies:
        - EC2DescribePolicy:
            InstanceID: i-07b5b982327a4f6f2
        - SQSSendMessagePolicy:
            QueueName: DakobedTransformQueue
        - arn:aws:iam::710339184759:policy/LambdaEC2PassRolePolicy
        - arn:aws:iam::710339184759:policy/LambdaLaunchEC2Policy
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedTranscriptions


  GetTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetTranscriptionFunction
      Runtime: python3.6
      Handler: handler.handler
      CodeUri: ./handlers/getTranscription/
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedTranscriptionsApi
            Path: /transcription/{transcriptionId}
            Method: GET
      Policies:
        - S3FullAccessPolicy:
              BucketName: dakobed-transcriptions
        - S3FullAccessPolicy:
              BucketName: dakobed-guitarset
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedTranscriptions

#  LaunchEC2Function:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: LaunchEC2Function
##      Role: arn:aws:iam::710339184759:role/Lamda-LaunchEC2
#      Runtime: python3.6
#      Handler: handler.lambda_handler
#      CodeUri: ./handlers/launchEC2/
#      Events:
#        SQSEvent:
#          Type: SQS
#          Properties:
#            Queue: arn:aws:sqs:us-west-2:710339184759:DakobedEC2Transforms
#            BatchSize: 10
#            Enabled: true
#      Policies:
#        - SQSSendMessagePolicy:
#            QueueName: TransformQueue
#        - arn:aws:iam::710339184759:policy/LambdaEC2PassRolePolicy
#        - arn:aws:iam::710339184759:policy/LambdaLaunchEC2Policy
#        - AWSLambdaBasicExecutionRole
#        - DynamoDBReadPolicy:
#            TableName: DakobedTranscriptions

  DakobedTranscriptionTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DakobedTranscriptionsTopic
      DisplayName: "Dakobed-Transcription-Topic"


  DakobedTranscriptionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DakobedTranscriptionQueue

  DakobedTransformQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DakobedTransformQueue

  DakobedQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DakobedTransformQueue
        - !Ref DakobedTranscriptionQueue
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: "*"
          Action: "sqs:*"
          Resource: "*"
          Condition:
            ArnEquals:
              "aws:SourceArn": !Ref DakobedTranscriptionTopic

  DakobedQueueToSnsSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !GetAtt DakobedTransformQueue.Arn
        Protocol: sqs
        RawMessageDelivery: true
        TopicArn: !Ref DakobedTranscriptionTopic


  StopEC2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StopEC2Function
      Runtime: python3.6
      Handler: handler.lambda_handler
      CodeUri: handlers/stopEC2/
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:710339184759:DakobedEC2StopQueue
            BatchSize: 10
            Enabled: false
      Policies:
        - arn:aws:iam::710339184759:policy/LambdaLaunchEC2Policy
        - AWSLambdaBasicExecutionRole

  GuitarsetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GuitarsetFunction
      Policies:
        - DynamoDBReadPolicy:
            TableName: DakobedGuitarSet
      CodeUri: handlers/guitarset/
      Handler: handler.lambda_handler
      Runtime: python3.7
      Events:
        GuitarsetApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedTranscriptionsApi
            Path: /guitarset
            Method: GET

  TabGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TabGeneratorFunction
      Policies:
        - DynamoDBReadPolicy:
            TableName: DakobedGuitarSet
      CodeUri: handlers/tab_generator/
      Handler: handler.lambda_handler
      Runtime: python3.7
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:710339184759:DakobedTabQueue
            BatchSize: 10
            Enabled: false

  TranscriptionDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranscriptionDetailFunction
      Runtime: python3.6
      Handler: handler.handler
      CodeUri: ./handlers/transcriptionDetail/
      Events:
        TranscriptionDetailApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedTranscriptionsApi
            Path: /transcription/{transcriptionId}
            Method: GET
      Policies:
        - S3FullAccessPolicy:
              BucketName: dakobed-transcriptions
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedTranscriptions
        - DynamoDBReadPolicy:
            TableName: DakobedGuitarSet


  GuitarSetDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GuitarSetDetailFunction
      Runtime: python3.6
      Handler: handler.handler
      CodeUri: ./handlers/guitarsetDetail/
      Events:
        TranscriptionDetailApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedTranscriptionsApi
            Path: /guitarset/{transcriptionId}
            Method: GET
      Policies:
        - S3FullAccessPolicy:
              BucketName: dakobed-transcriptions
        - S3FullAccessPolicy:
              BucketName: dakobed-guitarset
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedGuitarSet
